//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibaryPrograming.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLODUNC
    {
        public int ODUNCID { get; set; }
        public Nullable<int> KITAPID { get; set; }
        public Nullable<int> UYEID { get; set; }
        public Nullable<System.DateTime> ALISTARIH { get; set; }
        public Nullable<System.DateTime> GETIRECEGITARIH { get; set; }
        public Nullable<System.DateTime> GETIRDIGITARIH { get; set; }
    
        public virtual TBLUYE TBLUYE { get; set; }
    }
}
