//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibaryPrograming.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TBLUYE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLUYE()
        {
            this.TBLODUNCs = new HashSet<TBLODUNC>();
        }
    
        public int UYEID { get; set; }
        [Required(ErrorMessage ="Bu alaný boþ býrakamazsýnýz...!")]
        [StringLength(50,ErrorMessage ="En fazla 50 karakterlik ad gir")]
        public string UYEAD { get; set; }
        public string UYESOYAD { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLODUNC> TBLODUNCs { get; set; }
    }
}
